version: '3.4'
services:
  app:
    image: toucan-app
    container_name: toucan-app
    build:
      context: ./
      dockerfile: Dockerfile
    working_dir: /var/www/app
    volumes:
      - ../app:/var/www/app
    environment:
      - "DB_PORT=3306"
      - "DB_HOST=db"
    #command: sh -c "chown -R www-data:www-data /var/www/app && tail -f /dev/null"
    links:
      - db
    networks:
      - docker_network
  web:
    depends_on:
      - app
    image: nginx
    container_name: toucan-web
    volumes:
      - ../app:/var/www/app
      - ./nginx/vhost.conf:/etc/nginx/conf.d/default.conf
#      - ./nginx/certs:/etc/ssl/private
#      - ./nginx/certs:/etc/ssl/certs
    environment:
      - NGINX_HOST=toucan
      - NGINX_PORT=80
      - catch_workers_output=yes
    ports:
      - 80:80
      - 8443:443
      - 443:443
    networks:
      - docker_network
  db:
    image: mysql:5.7.12
    container_name: toucan-db
    ports:
      - "3306:3306"
    volumes:
      - ../db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=docker
    networks:
      - docker_network
  adminer:
    image: adminer:latest
    container_name: adminer
    restart: always
    ports:
      - 8088:8080
    networks:
      - docker_network
networks:
  docker_network:
    driver: bridge